### ISSUE TITLE
reg_coeff will cause 0 for any equations it's being used in

### ISSUE THREAD

**Issue by jcookeee** [AndrewLim1990/recommender_post#1]
Hi there, firstly thank you for your tutorial - I am a true beginner in data science. Unfortunately I have come unstuck when actually implementing the compute_error function. It seems I always get 0 for J, due to the fact that as soon as the statements with reg_coeff get used every output is 0.

for example 
beta_regularization = (**0** / 2) * (np.sum(beta**2))

if I am being a bit slow here forgive me, as I say above I'm very new to this

**Comment by jcookeee** [comment]
ah okay, the issue was actually **( 1 / 2 )** in the J calculation - i changed this to 0.5 and it worked fine

**Comment by AndrewLim1990** [comment]
Hi!

Thanks for the e-mail and sorry for the late reply ! I'll take a look into
this as well.

Good luck on your data science path.

Andrew
